newsletter:
  cron: "30 21 * * *"
  class: "NewsletterJob"
  active_job: true

sync:
  cron: "0 */1 * * *"
  class: "SyncJob"
  active_job: true

sync_video_podcast:
  cron: "30 23 * * *"
  class: "SyncVideosPodcastJob"
  active_job: true